source :rubygems

gem 'sinatra'
gem 'service_manager'
gem 'activerecord', '3.1.1'
gem 'sqlite3', '1.3.4'

group :development do
  gem 'rspec'
  gem 'cucumber'
  gem 'capybara'
  gem 'launchy'
  gem 'database_cleaner', '0.6.7'
end